stages:
  prepare_public_benchmark:
    cmd: python data/create_dataset.py
    deps:
      - data/create_dataset.py
      - data/raw/public_repo_security_peru_benchmark.xlsx
    outs:
      - data/public_repo_security_benchmark.csv
